# Use a slim JDK image for running the Spring Boot app
FROM eclipse-temurin:21.0.4_7-jdk

# Set the working directory inside the container
WORKDIR /app

# Copy the pre-built JAR file from your local machine into the container
COPY ./_3D-cost-estimator-0.0.1-SNAPSHOT.jar /app/app.jar

# Expose port 8080 (or whichever port your Spring Boot app runs on)
EXPOSE 8080

# Command to run the Spring Boot application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
